#
# This file is part of the CMaNGOS Project. See AUTHORS file for Copyright information
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#

language: cpp
cache: ccache

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# don't re-build for tags so that [publish binary] is not re-run
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^Last_.*/

# use ubuntu 18.04 VM
dist:
    bionic

# install dpendencies for linux
addons:
  apt:
    packages:
      - build-essential
      - libtool
      - make
      - cmake
      - libboost1.65-dev
      - libboost-system1.65-dev
      - libboost-program-options1.65-dev
      - libboost-thread1.65-dev
      - libboost-regex1.65-dev

# build matrix
matrix:
  include:
    # linux builds on gcc x64
    - os: linux
      arch: amd64
      compiler: gcc
      env:
        - CC=gcc-7
        - CXX=g++-7
    # linux builds on clang x64
    - os: linux
      arch: amd64
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++

    # linux builds on gcc ARM64
    - os: linux
      arch: arm64
      compiler: gcc
      env:
        - CC=gcc-7
        - CXX=g++-7
    # osx builds on clang x64
    - os: osx
      osx_image: xcode10
      arch: amd64
      compiler: clang
      env:
        - MYSQL_HOME=/usr/local/opt/mysql-client@5.7
      install:
        - brew install mysql-client@5.7
        - export OPENSSL_ROOT_DIR=$(brew --prefix openssl)

script: |-
  cmake --version
  mkdir _build
  mkdir _install
  cd _build
  export CCACHE_SLOPPINESS=pch_defines,time_macros
  cmake -DCMAKE_INSTALL_PREFIX=../_install -DBUILD_EXTRACTORS=ON -DBUILD_PLAYERBOT=ON ..
  make -j2
  make install
